[package]
name = "img"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["image", "advanced", "tokio"] }
glam = { version="0.30.8", features=["bytemuck"] }
bytemuck = "1.24.0"
rfd = "0.15.4"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = 3
strip = true
